color: blue
fieldLayouts:
  891fe5ca-95b0-4938-983e-0055db8d833a:
    cardView:
      - 'layoutElement:c7d47a81-41a0-4346-a3ac-7732a917098d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-12T08:34:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d2e5577-5ded-43c9-96e2-d4fc4c770fe9 # Link
            handle: blockquote
            includeInCards: true
            instructions: null
            label: Quote
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7d47a81-41a0-4346-a3ac-7732a917098d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-12T08:34:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d2e5577-5ded-43c9-96e2-d4fc4c770fe9 # Link
            handle: quoteAuthor
            includeInCards: false
            instructions: null
            label: Author
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0abd81cb-12ae-4474-ac49-58dc67faf286
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-12T08:34:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c9778b8-507c-4108-937d-6ceeabf35047 # Image
            handle: quoteImage
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f29566ca-a59b-46ad-82de-3b18c791abb3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 22664c7a-9a4f-469a-91f8-f6a5a9c42985
        userCondition: null
handle: blockquote
hasTitleField: false
icon: quote-left
name: Blockquote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
