color: blue
fieldLayouts:
  7c8f65e9-675e-4535-bab7-77e644a81e96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-28T04:43:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a58e287-e038-4eb7-ab2a-cf4cbdbe013d # Page content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb15c0fc-cdad-4ab0-91a1-c92354ff52f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 57ee79bd-1509-4d6a-9f60-400eb6ee7280
        userCondition: null
handle: callout
hasTitleField: false
icon: circle-exclamation
name: Callout
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
