color: green
description: null
fieldLayouts:
  fa6857cf-64a2-4aa3-8fd4-32920f194426:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:ae62e4a1-5f80-424a-b840-577dd1ca797c'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-19T08:34:05+00:00'
            elementCondition: null
            heading: Text
            type: craft\fieldlayoutelements\Heading
            uid: 1d37ff8b-4c3d-4a8b-8387-0907033853b1
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-18T11:25:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bdca3e3c-817d-4c15-9930-49daa730cb7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-18T11:25:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5fa79c32-8e3b-4ae6-a3c1-e6f21cfa02d1 # Text content - Block
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2e8a5ca-f0bb-4c90-a6b6-f502e856dfdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-18T09:24:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2f2dcbc9-3a85-4cab-aee6-7c21da58f818 # Vertical text alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6f8f82d-f7f8-4a43-9ced-d3ed5cf69896
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T08:34:05+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d5e634c4-44af-4c2b-9676-8d35ad784188
            userCondition: null
          -
            dateAdded: '2025-08-19T08:34:05+00:00'
            elementCondition: null
            heading: Image
            type: craft\fieldlayoutelements\Heading
            uid: fba434e8-0c01-4007-90e8-abb977db1680
            userCondition: null
          -
            dateAdded: '2025-08-13T13:07:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c9778b8-507c-4108-937d-6ceeabf35047 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae62e4a1-5f80-424a-b840-577dd1ca797c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-18T13:40:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3a9a31da-cd96-4080-8c3e-1a0e8d93ab9c # Aspect ratio
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c859405-39e1-4210-9307-8ae9f52fe840
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-18T09:24:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 544b5852-d1f2-4eb0-bee7-1eae61388349 # Horisontal image alignment
            handle: null
            includeInCards: false
            instructions: 'Align the image to the left of the text or the right of the text'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96b998f6-7fca-41b7-8409-9fed2609c5ac
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T08:34:05+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c2b03d9a-0472-42bd-bc69-fb47d41e1a19
            userCondition: null
          -
            dateAdded: '2025-08-19T08:34:05+00:00'
            elementCondition: null
            heading: Layout
            type: craft\fieldlayoutelements\Heading
            uid: 81bccbc2-bb7e-440e-b3b1-63efdba1df24
            userCondition: null
          -
            dateAdded: '2025-08-13T13:11:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d6485a63-635d-43c5-856a-c4ff44fefc9c # Block layout
            handle: null
            includeInCards: false
            instructions: 'Controls the block width and the layout position of the images and text'
            label: 'Block width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96e4fef9-dc84-47ce-946d-fbd524f6d3ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T06:27:45+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: d6485a63-635d-43c5-856a-c4ff44fefc9c # Block layout
                  layoutElementUid: 96e4fef9-dc84-47ce-946d-fbd524f6d3ed
                  operator: ni
                  uid: 86b5a0ac-790a-407b-adc3-3a4f97d589ad
                  values:
                    - wide
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 4553c171-a207-4790-a28f-fbe4c088a0c9 # Block Surface
            handle: null
            includeInCards: false
            instructions: null
            label: 'Block background'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e63d569-757e-43a7-9655-c896dfaabc0a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-20T20:08:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 07362c32-933d-4734-9245-ded033d68c43 # Make into section
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 604f5cc8-69aa-4dd2-9c7c-d74208887ec1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 907d21d4-79dc-4a22-83e2-14758ed1c1ba
        userCondition: null
handle: textWithImage
hasTitleField: true
icon: table-columns
name: 'Text with image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
