color: green
fieldLayouts:
  fa6857cf-64a2-4aa3-8fd4-32920f194426:
    cardView:
      - 'layoutElement:ae62e4a1-5f80-424a-b840-577dd1ca797c'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-18T11:25:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bdca3e3c-817d-4c15-9930-49daa730cb7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-18T11:25:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5fa79c32-8e3b-4ae6-a3c1-e6f21cfa02d1 # Text content - Block
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2e8a5ca-f0bb-4c90-a6b6-f502e856dfdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-18T09:24:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2f2dcbc9-3a85-4cab-aee6-7c21da58f818 # Vertical text alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6f8f82d-f7f8-4a43-9ced-d3ed5cf69896
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 907d21d4-79dc-4a22-83e2-14758ed1c1ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-13T13:07:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c9778b8-507c-4108-937d-6ceeabf35047 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae62e4a1-5f80-424a-b840-577dd1ca797c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-18T13:40:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3a9a31da-cd96-4080-8c3e-1a0e8d93ab9c # Aspect ratio
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c859405-39e1-4210-9307-8ae9f52fe840
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-18T09:24:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 544b5852-d1f2-4eb0-bee7-1eae61388349 # Horisontal image alignment
            handle: null
            includeInCards: false
            instructions: 'Align the image to the left of the text or the right of the text'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96b998f6-7fca-41b7-8409-9fed2609c5ac
            userCondition: null
            warning: null
            width: 100
        name: Image
        uid: 64a8945a-eb2c-4a4e-bbcf-c71a427f57d1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-13T13:11:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d6485a63-635d-43c5-856a-c4ff44fefc9c # Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96e4fef9-dc84-47ce-946d-fbd524f6d3ed
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: fd0ac9fb-c073-4f68-8201-6d007e3a580d
        userCondition: null
handle: textWithImage
hasTitleField: true
icon: table-columns
name: 'Text with image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
