color: green
fieldLayouts:
  fa6857cf-64a2-4aa3-8fd4-32920f194426:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-13T13:07:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9d42aa56-4a66-4d0b-b8a9-84a4cb387788 # Text block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1458bd3c-f95c-4372-82b2-08197fb56486
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 907d21d4-79dc-4a22-83e2-14758ed1c1ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-13T13:07:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c9778b8-507c-4108-937d-6ceeabf35047 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae62e4a1-5f80-424a-b840-577dd1ca797c
            userCondition: null
            warning: null
            width: 100
        name: Image
        uid: 64a8945a-eb2c-4a4e-bbcf-c71a427f57d1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-13T13:11:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d6485a63-635d-43c5-856a-c4ff44fefc9c # Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96e4fef9-dc84-47ce-946d-fbd524f6d3ed
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: fd0ac9fb-c073-4f68-8201-6d007e3a580d
        userCondition: null
handle: textWithImage
hasTitleField: false
icon: table-columns
name: 'Text with image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
