columnSuffix: null
handle: blockSurface
instructions: null
name: 'Block Surface'
searchable: false
settings:
  default: null
  palette: 'Block Background'
  setRandom: false
  useConfigFile: true
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
