columnSuffix: null
handle: blockLayout
instructions: 'This block can be constrained to the content pillar width or span the full width of the screen, this will affect the overall layout of the block.'
name: 'Block layout'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Normal Width'
        -
          - value
          - wide
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Full Width'
        -
          - value
          - full
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
