columnSuffix: null
handle: linkUrl
instructions: null
name: Link
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'My link'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
