headingLevels:
  - 3
  - 4
  - 5
  - 6
name: Medium
options:
  alignment:
    options:
      - left
      - right
toolbar:
  - heading
  - '|'
  - alignment
  - bold
  - italic
  - link
  - bulletedList
  - numberedList
  - todoList
